version: '3'
services:
  db:
    image: 'postgres'
    container_name: 'websocket_postgres'
    restart: always

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

    ports:
      - "5432:5432"